### ISSUE TITLE
index.js, overbodige const

### ISSUE THREAD

**Issue by RobinStut** [veerleprins/featureDatingApp#1]
In je index.js file op regel 7 staat er:
```javascript
const dotenv = require('dotenv').config();
```
Het is niet nodig om voor deze regel een const te gebruiken, je roept deze ook niet meer aan.
Dit kan je vervangen door:
```javascript
require('dotenv').config()
```

**Comment by veerleprins** [comment]
I've changed it, thanks! 👍
