### ISSUE TITLE
index.js, allUsers wordt niet gebruikt

### ISSUE THREAD

**Issue by RobinStut** [veerleprins/featureDatingApp#2]
https://github.com/veerleprins/featureDatingApp/blob/4fd7d24c96f57c0e39cdcc1d0b7ed78ab0c14a27/index.js#L67

Deze let wordt niet meer gebruikt in je index.js bestand. Ik geloof dat je deze regel kan deleten

**Comment by veerleprins** [comment]
I've changed my code so I'm not using allUsers anymore, thanks 😄 !
