### ISSUE TITLE
index.ejs, comments

### ISSUE THREAD

**Issue by RobinStut** [veerleprins/featureDatingApp#3]
https://github.com/veerleprins/featureDatingApp/blob/4fd7d24c96f57c0e39cdcc1d0b7ed78ab0c14a27/view-ejs/index.ejs#L32

https://github.com/veerleprins/featureDatingApp/blob/4fd7d24c96f57c0e39cdcc1d0b7ed78ab0c14a27/view-ejs/filters.ejs#L32

https://github.com/veerleprins/featureDatingApp/blob/4fd7d24c96f57c0e39cdcc1d0b7ed78ab0c14a27/view-ejs/partials/head.ejs#L3

je kan het beste comments niet in je code laten zitten, behalve als deze een beschrijving geven aan wat er gebeurd.

**Comment by veerleprins** [comment]
Oh, I totally forgot this. Thank you! 😄
