### ISSUE TITLE
style.css, 👍

### ISSUE THREAD

**Issue by RobinStut** [veerleprins/featureDatingApp#5]
https://github.com/veerleprins/featureDatingApp/blob/4fd7d24c96f57c0e39cdcc1d0b7ed78ab0c14a27/static/styles/style.css#L23

Je styling ziet er netjes en geordend uit!
Je splitst je code netjes op, voor elke element.
Misschien zou je kunnen kijken of je deze "hoofdstukken" zou kunnen opsplitsen in losse css bestanden per "hoofdstuk".
Zo kan je het voor jezelf gemakkelijk maken bij het aanpassen van bepaalde onderdelen, en hoeven niet alle css "hoofdstukken" op elke pagina ingeladen te worden.

**Comment by veerleprins** [comment]
As far as I know, we cannot use different CSS files. (< Rules from CMD)
